// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class PFPBPopPoint;
@class PFPBPopPoint_Builder;
@class PFPBPopStroke;
@class PFPBPopStroke_Builder;

@interface PfpopRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PFPBPopPoint : PBGeneratedMessage {
@private
  BOOL hasCreateTime_:1;
  BOOL hasX_:1;
  BOOL hasY_:1;
  BOOL hasPressure_:1;
  Float64 createTime;
  Float32 x;
  Float32 y;
  Float32 pressure;
}
- (BOOL) hasX;
- (BOOL) hasY;
- (BOOL) hasCreateTime;
- (BOOL) hasPressure;
@property (readonly) Float32 x;
@property (readonly) Float32 y;
@property (readonly) Float64 createTime;
@property (readonly) Float32 pressure;

+ (PFPBPopPoint*) defaultInstance;
- (PFPBPopPoint*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PFPBPopPoint_Builder*) builder;
+ (PFPBPopPoint_Builder*) builder;
+ (PFPBPopPoint_Builder*) builderWithPrototype:(PFPBPopPoint*) prototype;

+ (PFPBPopPoint*) parseFromData:(NSData*) data;
+ (PFPBPopPoint*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PFPBPopPoint*) parseFromInputStream:(NSInputStream*) input;
+ (PFPBPopPoint*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PFPBPopPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PFPBPopPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PFPBPopPoint_Builder : PBGeneratedMessage_Builder {
@private
  PFPBPopPoint* result;
}

- (PFPBPopPoint*) defaultInstance;

- (PFPBPopPoint_Builder*) clear;
- (PFPBPopPoint_Builder*) clone;

- (PFPBPopPoint*) build;
- (PFPBPopPoint*) buildPartial;

- (PFPBPopPoint_Builder*) mergeFrom:(PFPBPopPoint*) other;
- (PFPBPopPoint_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PFPBPopPoint_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasX;
- (Float32) x;
- (PFPBPopPoint_Builder*) setX:(Float32) value;
- (PFPBPopPoint_Builder*) clearX;

- (BOOL) hasY;
- (Float32) y;
- (PFPBPopPoint_Builder*) setY:(Float32) value;
- (PFPBPopPoint_Builder*) clearY;

- (BOOL) hasCreateTime;
- (Float64) createTime;
- (PFPBPopPoint_Builder*) setCreateTime:(Float64) value;
- (PFPBPopPoint_Builder*) clearCreateTime;

- (BOOL) hasPressure;
- (Float32) pressure;
- (PFPBPopPoint_Builder*) setPressure:(Float32) value;
- (PFPBPopPoint_Builder*) clearPressure;
@end

@interface PFPBPopStroke : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasOffset_:1;
  int32_t type;
  PFPBPopPoint* offset;
  NSMutableArray* mutablePointsList;
}
- (BOOL) hasOffset;
- (BOOL) hasType;
@property (readonly, retain) PFPBPopPoint* offset;
@property (readonly) int32_t type;
- (NSArray*) pointsList;
- (PFPBPopPoint*) pointsAtIndex:(int32_t) index;

+ (PFPBPopStroke*) defaultInstance;
- (PFPBPopStroke*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PFPBPopStroke_Builder*) builder;
+ (PFPBPopStroke_Builder*) builder;
+ (PFPBPopStroke_Builder*) builderWithPrototype:(PFPBPopStroke*) prototype;

+ (PFPBPopStroke*) parseFromData:(NSData*) data;
+ (PFPBPopStroke*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PFPBPopStroke*) parseFromInputStream:(NSInputStream*) input;
+ (PFPBPopStroke*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PFPBPopStroke*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PFPBPopStroke*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PFPBPopStroke_Builder : PBGeneratedMessage_Builder {
@private
  PFPBPopStroke* result;
}

- (PFPBPopStroke*) defaultInstance;

- (PFPBPopStroke_Builder*) clear;
- (PFPBPopStroke_Builder*) clone;

- (PFPBPopStroke*) build;
- (PFPBPopStroke*) buildPartial;

- (PFPBPopStroke_Builder*) mergeFrom:(PFPBPopStroke*) other;
- (PFPBPopStroke_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PFPBPopStroke_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOffset;
- (PFPBPopPoint*) offset;
- (PFPBPopStroke_Builder*) setOffset:(PFPBPopPoint*) value;
- (PFPBPopStroke_Builder*) setOffsetBuilder:(PFPBPopPoint_Builder*) builderForValue;
- (PFPBPopStroke_Builder*) mergeOffset:(PFPBPopPoint*) value;
- (PFPBPopStroke_Builder*) clearOffset;

- (NSArray*) pointsList;
- (PFPBPopPoint*) pointsAtIndex:(int32_t) index;
- (PFPBPopStroke_Builder*) replacePointsAtIndex:(int32_t) index with:(PFPBPopPoint*) value;
- (PFPBPopStroke_Builder*) addPoints:(PFPBPopPoint*) value;
- (PFPBPopStroke_Builder*) addAllPoints:(NSArray*) values;
- (PFPBPopStroke_Builder*) clearPointsList;

- (BOOL) hasType;
- (int32_t) type;
- (PFPBPopStroke_Builder*) setType:(int32_t) value;
- (PFPBPopStroke_Builder*) clearType;
@end

